name: Test Front Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.18.0'

      - name: Configurar npm
        run: npm install -g npm@12.0.0

      - name: Verificar versões
        run: |
          node -v
          npm -v

      - name: Instalar dependências
        run: npm ci

      - name: Gerar build de produção
        run: npm run build

      - name: Verificar arquivos gerados
        run: ls -la dist/erp
