name: Test SSH

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Testar conexão SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            echo "Conexão SSH realizada com sucesso"
            whoami
            pwd
